DLDK_Forum/DLDK_Forum/Areas/Admin/Controllers/BaiVietsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DLDK_Forum.Models;

namespace DLDK_Forum.Areas.Admin.Controllers
{
    public class BaiVietsController : Controller
    {
        private MyDB db = new MyDB();

        // GET: Admin/BaiViets
        public ActionResult Index()
        {
            var baiViets = db.BaiViets.Include(b => b.ChuDe).Include(b => b.NguoiDung);
            return View(baiViets.ToList());
        }

        // GET: Admin/BaiViets/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Create
        public ActionResult Create()
        {
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe");
            ViewBag.Email = new SelectList(db.NguoiDungs, "Email", "HoTen");
            return View();
        }

        // POST: Admin/BaiViets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaBaiViet,Email,Noidung,DuongDanHinhAnh,MaChuDe,TinhTrang,TieuDe,ThoiGian")] BaiViet baiViet)
        {
            if (ModelState.IsValid)
            {
                db.BaiViets.Add(baiViet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", baiViet.MaChuDe);
            ViewBag.Email = new SelectList(db.NguoiDungs, "Email", "HoTen", baiViet.Email);
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", baiViet.MaChuDe);
            ViewBag.Email = new SelectList(db.NguoiDungs, "Email", "HoTen", baiViet.Email);
            return View(baiViet);
        }

        // POST: Admin/BaiViets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaBaiViet,Email,Noidung,DuongDanHinhAnh,MaChuDe,TinhTrang,TieuDe,ThoiGian")] BaiViet baiViet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(baiViet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaChuDe = new SelectList(db.ChuDes, "MaChuDe", "TenChuDe", baiViet.MaChuDe);
            ViewBag.Email = new SelectList(db.NguoiDungs, "Email", "HoTen", baiViet.Email);
            return View(baiViet);
        }

        // GET: Admin/BaiViets/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BaiViet baiViet = db.BaiViets.Find(id);
            if (baiViet == null)
            {
                return HttpNotFound();
            }
            return View(baiViet);
        }

        // POST: Admin/BaiViets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            BaiViet baiViet = db.BaiViets.Find(id);
            db.BaiViets.Remove(baiViet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed_2()
        {
            string id = Request.Form["check"].ToString();
            BaiViet baiViet = db.BaiViets.Find(id);
            db.BaiViets.Remove(baiViet);
            db.SaveChanges();
            return RedirectToAction("QuanLyBaiViet","QuanLy");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DLDK_Forum/DLDK_Forum/Areas/Admin/Controllers/NguoiDungsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DLDK_Forum.Models;

namespace DLDK_Forum.Areas.Admin.Controllers
{
    public class NguoiDungsController : Controller
    {
        private MyDB db = new MyDB();

        // GET: Admin/NguoiDungs
        public ActionResult Index()
        {
            return View(db.NguoiDungs.ToList());
        }

        // GET: Admin/NguoiDungs/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // GET: Admin/NguoiDungs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/NguoiDungs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Email,HoTen,QuyenAdmin,MatKhau,AnhDaiDien,GioiTinh,MoTa")] NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.NguoiDungs.Add(nguoiDung);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(nguoiDung);
        }

        // GET: Admin/NguoiDungs/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // POST: Admin/NguoiDungs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Email,HoTen,QuyenAdmin,MatKhau,AnhDaiDien,GioiTinh,MoTa")] NguoiDung nguoiDung)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nguoiDung).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(nguoiDung);
        }

        // GET: Admin/NguoiDungs/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            if (nguoiDung == null)
            {
                return HttpNotFound();
            }
            return View(nguoiDung);
        }

        // POST: Admin/NguoiDungs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            db.NguoiDungs.Remove(nguoiDung);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed_2()
        {
            string id = Request.Form["check"].ToString();
            NguoiDung nguoiDung = db.NguoiDungs.Find(id);
            db.NguoiDungs.Remove(nguoiDung);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DLDK_Forum/DLDK_Forum/Areas/Admin/Controllers/QuanLyController.cs
using DLDK_Forum.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DLDK_Forum.Areas.Admin.Controllers
{
    public class QuanLyController : Controller
    {
        MyDB db = new MyDB();
        // GET: Admin/QuanLy
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult QuanLyNguoiDung()
        {
            ViewBag.DSND = db.NguoiDungs.ToList();
            return View();
        }
        public ActionResult QuanLyBaiViet()
        {
            ViewBag.DSBV = db.BaiViets.ToList();
            return View();
        }
        public ActionResult QuanLyPhanHoi()
        {
            ViewBag.DSPH = db.PhanHois.ToList();
            return View();
        }
    }
}

DLDK_Forum/DLDK_Forum/Areas/Admin/Views/QuanLy/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanLy.cshtml";
}

<h2>Halo!</h2>

DLDK_Forum/DLDK_Forum/Areas/Admin/Views/QuanLy/QuanLyBaiViet.cshtml
@{
    ViewBag.Title = "QuanLyBaiViet";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanLy.cshtml";
}
@using DLDK_Forum.Models;
@{
    List<BaiViet> dsbv = ViewBag.DSBV;
}

<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản Lý Bài Viết</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Home">DLDK Trip</a></li>

                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->


<div class="card">
    <div class="card-header">
        <h3 class="card-title">Các Bài Viết</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0" style="height: 600px;">
        <table class="table table-head-fixed text-nowrap">
            <thead>
                <tr>
                    <th>Mã bài viết</th>
                    <th>Tiêu đề</th>
                    <th>Tác giả</th>
                    <th>Ngày</th>
                    <th>Trạng thái</th>
                    <th>Hành động</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in dsbv)
                {
                    <tr>
                        <td>@item.MaBaiViet</td>
                        <td>
                            <a href="/Post/Single_Post?idPost=@item.MaBaiViet">
                                @item.TieuDe
                            </a>
                        </td>
                        <td>@item.NguoiDung.HoTen</td>
                        <td>@item.ThoiGian</td>
                        <td>Đã đăng</td>
                        <td>
                            @*<a id="@item.MaBaiViet" href="/Admin/BaiViets/Delete/@item.MaBaiViet">
                                Delete
                            </a>*@
                            
                            <!--Modal example-->
                            <div class="container">                                
                                <!-- Trigger the modal with a button -->
                                @{ 
                                    var str = "#myModal" + @item.MaBaiViet.ToString();
                                    var strid = "myModal" + @item.MaBaiViet.ToString();
                                }
                                <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target=@str>Xoá</button>

                                <!-- Modal -->
                                <div class="modal fade" id=@strid role="dialog">
                                    <div class="modal-dialog">

                                        <!-- Modal content-->
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                                                <h4 class="modal-title">Bạn có muốn xoá bài viết???</h4>
                                            </div>
                                            <div class="modal-body">
                                                <h5>@item.TieuDe</h5>
                                                <p>@item.Noidung...</p>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                                @using (Html.BeginForm("DeleteConfirmed_2", "BaiViets",FormMethod.Post))
                                                {
                                                    @Html.AntiForgeryToken()

                                                    <div class="form-actions no-color"> 
                                                        <input type="text" name="check" value = @item.MaBaiViet hidden/>
                                                        <input type="submit" value="Delete" class="btn btn-default" />                                                     

                                                    </div>
                                                }
                                            </div>
                                            
                                        </div>

                                    </div>
                                </div>

                            </div>
                            <!--End Modal-->
                        </td>
                    </tr>

                }



            </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->

DLDK_Forum/DLDK_Forum/Areas/Admin/Views/QuanLy/QuanLyNguoiDung.cshtml
@{
    ViewBag.Title = "QuanLyNguoiDung";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanLy.cshtml";
}
@using DLDK_Forum.Models;
@{
    List<NguoiDung> dsnd = ViewBag.DSND;
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản Lý Người Dùng</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Home">DLDK Trip</a></li>
                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->




<div class="card">
    <div class="card-header">
        <h3 class="card-title">Các người dùng</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0" style="height: 600px;">
        <table class="table table-head-fixed text-nowrap">
            <thead>
                <tr>
                    <th>N</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Date</th>
                    <th>Is Admin</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in dsnd)
                {
                <tr>
                    <td>1</td>
                    <td>
                        <a href="/Home/Account?idAccount=@item.Email">
                            @item.HoTen
                        </a>
                    </td>
                    <td> @item.Email </td>
                    <td>1-3-2014</td>
                    @if (@item.QuyenAdmin == 1)
                    {
                        <td><input type="checkbox" checked="checked"></td>
                    }
                    else
                    {
                        <td><input type="checkbox"></td>
                    }
                <td>
                    <a href="manage_users.html">
                        Delete
                    </a>
                    <!--Modal example-->
                    <div class="container">
                        <!-- Trigger the modal with a button -->
                        @{
                            var str = "#myModal" + @item.Email.ToString();
                            var strid = "myModal" + @item.Email.ToString();
                        }
                        <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target=@str>Xoá</button>

                        <!-- Modal -->
                        <div class="modal fade" id=@strid role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        @*<button type="button" class="close" data-dismiss="modal">&times;</button>*@
                                        <h4 class="modal-title">Bạn có muốn xoá tài khoản???</h4>
                                    </div>
                                    <div class="modal-body">
                                        <h5>@item.Email</h5>
                                        <p>@item.HoTen</p>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        @using (Html.BeginForm("DeleteConfirmed_2", "NguoiDungs", FormMethod.Post))
                                        {
                                            @Html.AntiForgeryToken()

                                            <div class="form-actions no-color">
                                                <input type="text" name="check" value=@item.Email hidden />
                                                <input type="submit" value="Delete" class="btn btn-default" />

                                            </div>
                                        }
                                    </div>

                                </div>

                            </div>
                        </div>

                    </div>
                    <!--End Modal-->
                </td>

                </tr>

                }
            </tbody>
            
        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->
<!-- /.content -->

DLDK_Forum/DLDK_Forum/Areas/Admin/Views/QuanLy/QuanLyPhanHoi.cshtml
@{
    ViewBag.Title = "QuanLyNguoiDung";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutQuanLy.cshtml";
}
@using DLDK_Forum.Models;
@{
    List<PhanHoi> dsph = ViewBag.DSPH;
}
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0 text-dark">Quản Lý Phản Hồi</h1>
            </div>
            <!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="~/Home/Home">DLDK Trip</a></li>
                </ol>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<!-- Main content -->




<div class="card">
    <div class="card-header">
        <h3 class="card-title">Các phản hổi</h3>

        <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
                <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                <div class="input-group-append">
                    <button type="submit" class="btn btn-default">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body table-responsive p-0" style="height: 600px;">
        <table class="table table-head-fixed text-nowrap">
            <thead>
                <tr>
                    <th>STT</th>
                    <th>Tên người dùng</th>
                    <th>Email</th>
                    <th>Ngày</th>
                    <th>Nội dung</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in dsph)
                {
                <tr>
                    <td>1</td>
                    <td> @item.HoTen </td>
                    <td>@item.Email</td>
                    <td>@item.ThoiGian</td>
                    <td>@item.NoiDung</td>
                    <td>
                        <a href="">
                            Delete
                        </a>
                    </td>
                </tr>

                }
            </tbody>

        </table>
    </div>
    <!-- /.card-body -->
</div>
<!-- /.card -->
<!-- /.content -->