DLDK_Forum/DLDK_Forum/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DLDK_Forum.Models;
using DLDK_Forum.Models.Function;

namespace DLDK_Forum.Controllers
{
    public class PostController : Controller
    {
       private MyDB MyDBContext = new MyDB();

        // GET: Post
        public ActionResult ListPost(string idChuDe,string search="")
        {
            BaiVietDAO DAO = new BaiVietDAO();
            List<BaiViet> BV = new List<BaiViet>();
            if (idChuDe == "") {
                BV = MyDBContext.BaiViets.OrderBy(s=>s.ThoiGian).ToList();
            }
            else
            {
                BV = DAO.GetBaiViets(idChuDe).OrderBy(s=>s.ThoiGian).ToList();
            }
            return View(BV);
        }
        
        public ActionResult TableOfContents()
        {
            List<ChuDe> Topics = MyDBContext.ChuDes.Where(s=>s.TenChuDe!="Khác").OrderBy(s=>s.TenChuDe).ToList();
            return View(Topics);
        }
        public ActionResult Single_Post(string idPost)
        {
            var BaiViet = MyDBContext.BaiViets.SingleOrDefault(s => s.MaBaiViet == idPost);
            return View(BaiViet);
        }
        public ActionResult NewPost()
        {
            return View();
        }
        [HttpPost]
        public ActionResult dangbai(BaiViet BV,HttpPostedFileBase file)
        {
            if (Session["User"] == null)
            {
                TempData["Error"] = "Bạn phải đăng nhập!!";
                return Redirect("/Home/Login_Logout");
            }
            BaiVietDAO DAO = new BaiVietDAO();
            NguoiDung ND = (NguoiDung)Session["User"];
            BV.Email = ND.Email;
            BV.TinhTrang = 1;
            BV.ThoiGian = DateTime.Now;
            BV.MaBaiViet = DAO.BaiMoi();
            if (file != null && file.ContentLength > 0)
            {
                string filename = Path.GetFileName(file.FileName);
                string imgpath = Path.Combine(Server.MapPath("~/images/"), filename);
                file.SaveAs(imgpath);
                BV.DuongDanHinhAnh = "images/" + file.FileName;
            }
            else
            {
                BV.DuongDanHinhAnh = "images/post_default.jpg";
            }
            MyDBContext.BaiViets.Add(BV);
            MyDBContext.SaveChanges();
            return Redirect("/Post/Single_Post?idPost="+BV.MaBaiViet);
        }
        [HttpPost]
        public ActionResult binhluan( string NoiDung, string idPost)
        {
            if (Session["User"] == null)
            {
                return Redirect("/Home/Login_Logout");
            }
            NguoiDung ND = (NguoiDung)Session["User"];
            BinhLuan BL = new BinhLuan();
            BL.NoiDung = NoiDung;
            BL.MaBaiViet = idPost;
            BL.ThoiGian = DateTime.Now;
            BL.Email = ND.Email;
            MyDBContext.BinhLuans.Add(BL);
            MyDBContext.SaveChanges();
            return Redirect("/Post/Single_Post?idPost="+idPost);           
        }
        [HttpPost]
        public ActionResult bieucam(CamXuc CX)
        {
            if (Session["User"] == null)
            {
                @TempData["Error"] = "Bạn cần đăng nhập!";
                return RedirectToAction("Login_Logout", "Home");
            }
            CamXucDAO DAO = new CamXucDAO();
            NguoiDung user = (NguoiDung)Session["User"];
            var CX_cu = MyDBContext.CamXucs.SingleOrDefault(s => s.Email == user.Email & s.MaBaiViet == CX.MaBaiViet);
            if (CX_cu != null)
            {
                CX_cu.Thich = CX.Thich;
                //db.Entry(dep).State = System.Data.Entity.EntityState.Modified;
                MyDBContext.Entry(CX_cu).State = System.Data.Entity.EntityState.Modified;
            }
            else
            {
                CX.Email = user.Email;
                MyDBContext.CamXucs.Add(CX);
            }
            MyDBContext.SaveChanges();
            return Redirect(Request.UrlReferrer.ToString());
            //return View("Single_Post","Post",idPost);
        }
        //[HttpPost]
        //public ActionResult Search(string search)
        //{

        //    var a = MyDBContext.BaiViets.Where(s => s.TieuDe.Contains(search)).ToList();
        //}
    }
}

DLDK_Forum/DLDK_Forum/Views/Post/ListPost.cshtml
@using System.Globalization
@using DLDK_Forum.Models
@using DLDK_Forum.Models.Function
@model IEnumerable<DLDK_Forum.Models.BaiViet>
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="~/Content/css/list_post.css">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="~/Content/fontawesome-free-5.14.0-web/css/all.css">
    <title>DLDK TRIP | Chủ đề</title>
    @*<link rel="stylesheet" href="~/Content/css/Layout.css">*@
</head>
<body>
    @Html.Partial("~/Views/Shared/header.cshtml")
    <div class="content">
        <div class="container">
            <div class="main">
                <!-- <div class="col-1"></div> -->
                <div class="col-2">
                    @foreach (var item in Model)
                    {
                        <div class="post">
                            <div class="post-left">
                                <div class="post-image">
                                    <img src="~/@item.DuongDanHinhAnh" alt="">
                                </div>
                                <div class="post-react">
                                    @{
                                        var Thich = item.CamXucs.Where(s => s.Thich == 1).Count();
                                        var KThich = item.CamXucs.Where(s => s.Thich == 0).Count();
                                        var BinhLuan = item.BinhLuans.Count();
                                    }
                                    @if (@Session["User"] != null)
                                    {

                                        CamXucDAO DAO = new CamXucDAO();
                                        NguoiDung user = (NguoiDung)Session["User"];
                                        var CX = DAO.getCamXuc(user.Email, item.MaBaiViet);
                                        if (CX != null)
                                        {
                                            if (@CX.Thich == 1)
                                            {
                                                <div class="i-container" style="background:rgb(253, 96, 96);"><i class="far fa-thumbs-up"></i><span>@Thich</span> </div>
                                                <div class="i-container"><i class="far fa-thumbs-down"></i> <span>@KThich</span></div>
                                            }
                                            else if (CX.Thich == 0)
                                            {
                                                <div class="i-container"><i class="far fa-thumbs-up"></i><span>@Thich</span> </div>
                                                <div class="i-container" style="background:rgb(124, 124, 124);"><i class="far fa-thumbs-down" ></i> <span>@KThich</span></div>
                                            }
                                            else
                                            {
                                                <div class="i-container"><i class="far fa-thumbs-up"></i><span>@Thich</span> </div>
                                                <div class="i-container"><i class="far fa-thumbs-down"></i> <span>@KThich</span></div>
                                            }
                                            <div class="i-container"><i class="far fa-comment"></i><span>@BinhLuan</span></div>

                                        }
                                        else
                                        {
                                            <div class="i-container"><i class="far fa-thumbs-up"></i><span>@Thich</span> </div>
                                            <div class="i-container"><i class="far fa-thumbs-down"></i> <span>@KThich</span></div>
                                            <div class="i-container"><i class="far fa-comment"></i><span>@BinhLuan</span></div>
                                        }

                                    }
                                    else
                                    {
                                        <div class="i-container"><i class="far fa-thumbs-up"></i><span>@Thich</span> </div>
                                        <div class="i-container"><i class="far fa-thumbs-down"></i> <span>@KThich</span></div>
                                        <div class="i-container"><i class="far fa-comment"></i><span>@BinhLuan</span></div>
                                    }

                                </div>
                            </div>
                            <div class="post-right">
                                <div class="time">
                                    <div class="hour">
                                        <p>@item.ThoiGian.ToString("hh:mm")</p>
                                    </div>
                                    <div class="date">
                                        <p class="day">@item.ThoiGian.Day</p>
                                        <p class="month-year">tháng @item.ThoiGian.Month @item.ThoiGian.Year</p>
                                    </div>
                                </div>
                                <div class="author" onclick="window.open('/Home/Account?idAccount=@item.Email','_self')">
                                    <img src="~/@item.NguoiDung.AnhDaiDien" alt="">
                                    <h4>@item.NguoiDung.HoTen</h4>
                                </div>
                                <div class="description">
                                    <h2 class="title">
                                        @item.TieuDe
                                    </h2>
                                    @if (item.Noidung.Length <= 300)
                                    {
                                        <p class="sub-title">
                                            @item.Noidung...
                                        </p>
                                    }
                                    else
                                    {
                                        <p class="sub-title">
                                             @item.Noidung.Substring(0, 300)...
                                        </p>
                                    }

                                </div>
                                <a href="/Post/Single_Post?idPost=@item.MaBaiViet" class="read">ĐỌC THÊM</a>
                            </div>
                        </div>
                    }
                </div>
                <div class="col-3">
                    @Html.Action("TableOfContents","Post")
                </div>
            </div>

        </div>
    </div>
    @Html.Partial("~/Views/Shared/footer.cshtml")

</body>

</html>

DLDK_Forum/DLDK_Forum/Views/Post/NewPost.cshtml
@{
    ViewBag.Title = "ListPost";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DLDK TRIP | Bài viết mới</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Work+Sans">
    <link rel="stylesheet" href="~/Content/css/new_post.css">
</head>


<body>
    @Html.Partial("~/Views/Shared/header.cshtml")
    <div class="main">
        <div class="container1">
            <h1>Viết nên trải nghiệm của bạn</h1>
            <p>“Một khi bị nhiễm niềm đam mê du lịch, chẳng có phương thuốc nào có thể hóa giải, và tôi biết rằng tôi sẽ hạnh phúc khi có căn bệnh này cho đến hết cuộc đời.”</p>
            <form action="/Post/dangbai" method="post" enctype="multipart/form-data">
                <ul>
                    <li>

                        <select name="MaChuDe" id="topics" required>
                            <option value="">Chủ đề...</option>
                            <option value="CD02">Hà Nội</option>
                            <option value="CD07">Thành Phố Hồ Chí Minh</option>
                            <option value="CD01">Sapa</option>
                            <option value="CD08">Miền Tây</option>
                            <option value="CD05">Nha Trang</option>
                            <option value="CD06">Đà Lạt</option>
                            <option value="CD04">Huế-Đà Nẵng-Quảng Nam</option>
                            <option value="CD09">Phú Quốc</option>
                            <option value="CD03">Ninh Bình</option>
                            <option value="CD00">Khác</option>
                        </select>
                    </li>
                    <li>
                        <label for="title">Tiêu đề</label> <input type="text" name="TieuDe" required>
                    </li>
                    <li>
                        <label for="image-post">Ảnh</label> <input type="file" name="file">
                    </li>
                    <li>
                        <label for="content">Nội dung</label> <textarea name="Noidung" id="" cols="30" rows="20" required></textarea>
                    </li>
                </ul>
                <input type="submit" value="Thêm" class="btn">
            </form>
        </div>

    </div>
    @Html.Partial("~/Views/Shared/footer.cshtml")

</body>

</html>

DLDK_Forum/DLDK_Forum/Views/Post/Single_Post.cshtml
@model DLDK_Forum.Models.BaiViet
@using DLDK_Forum.Models;
@using DLDK_Forum.Models.Function;
@{
    Layout = null;
    var noidung = Model.Noidung.Split('\n');
  
}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed&display=swap" rel="stylesheet">
    <title>DLDK TRIP | Bài viết</title>
    <link rel="stylesheet" type="text/css" href="~/Content/fontawesome-free-5.14.0-web/css/all.css">
    <link rel="stylesheet" href="~/Content/css/single_blog.css">
</head>

<body>

    <div class="title_container" style="background:url(/@Model.DuongDanHinhAnh);background-position: center;background-size: cover;background-repeat: no-repeat;background-attachment: fixed;">
        @Html.Partial("~/Views/Shared/header.cshtml")
        <div class="title">
            <div class="title1">
                <span>@Model.ThoiGian.Day . @Model.ThoiGian.Month . @Model.ThoiGian.Year<span>•</span>By @Model.NguoiDung.HoTen </span>
                <h1>@Model.TieuDe</h1>
            </div>
        </div>
    </div>

    <div class="content">
        <div class="row">
            <div class="col-1">
                <br>
                @foreach (var item in noidung)
                {
                    <p>&emsp;@item</p>
                }
                <br>
                <hr>
                <div class="comment-container">
                    <form class="post-react" action="/Post/bieucam?MaBaiViet=@Model.MaBaiViet" method="post">
                        @{
                            var Thich = Model.CamXucs.Where(s => s.Thich == 1).Count();
                            var KThich = Model.CamXucs.Where(s => s.Thich == 0).Count();
                            var BinhLuan = Model.BinhLuans.Count();
                        }
                        @if (@Session["User"] != null)
                        {

                            CamXucDAO DAO = new CamXucDAO();
                            NguoiDung user = (NguoiDung)Session["User"];
                            var CX = DAO.getCamXuc(user.Email, Model.MaBaiViet);
                            if (CX != null)
                            {
                                if (@CX.Thich == 1)
                                {
                                    <style>
                                        button.i-container:nth-child(2) {
                                            background: rgb(253, 96, 96);
                                        }
                                        button.i-container:nth-child(3) {
                                            background: #fff;
                                        }
                                    </style>
                                }
                                else
                                {
                                    <style>
                                         button.i-container:nth-child(2) {
                                            background: #fff;
                                        }
                                        button.i-container:nth-child(3) {
                                            background: rgb(124, 124, 124);
                                        }
                                    </style>
                                }
                            }                           
                        }
                            <button type="submit" value="1" name="thich" class="i-container"><i class="far fa-thumbs-up"></i><span>@Thich</span></button>
                            <button type="submit" value="0" name="thich" class="i-container"><i class="far fa-thumbs-down"></i><span>@KThich</span></button>
                            <div class="i-container"><i class="far fa-comment"></i><span>@BinhLuan</span></div>                      
                     </form>
                    <div class="count-container">
                        <p>@Model.BinhLuans.Count() Bình luận</p>
                    </div>
                    <ul>
                        @foreach (var item in Model.BinhLuans.OrderBy(s => s.ThoiGian))
                        {
                            <li class="comment">
                                <div class="avt-user">
                                    <img src="~/@item.NguoiDung.AnhDaiDien" alt="">
                                </div>
                                <div class="comment-body">
                                    <h4>@item.NguoiDung.HoTen</h4>
                                    <span>@item.ThoiGian.ToString()</span>
                                    <p>@item.NoiDung</p>
                                    @*<p class="btn">Trả lời</p>*@
                                </div>
                            </li>
                        }
                    </ul>
                    <hr>
                    @if (Session["User"] != null)
                    {

                        <div class="new-comment">
                            <h4>Thêm bình luận</h4>
                            <form action="/Post/binhluan?idPost=@Model.MaBaiViet" method="post">
                                <div class="message-container">
                                    <textarea name="NoiDung" cols="100" rows="20"></textarea>
                                </div>
                                <div class="btn-container">
                                    <input type="submit" class="btn-add" value="Thêm">
                                </div>
                            </form>
                        </div>
                    }
                </div>
            </div>
            <div class="col-2">
                <div class="author">
                    <div class="image-container">
                        <img src="~/@Model.NguoiDung.AnhDaiDien" alt="">
                    </div>
                    <h3>@Model.NguoiDung.HoTen</h3>
                    <hr>
                    <p>Du lịch là một trải nghiệm vô cùng thú vị để bản khám phá thế giới, Thế giới bao la còn bao điều bạn chưa từng khám phá ra, Xách ba lô lên và đi thôi</p>
                    <div class="btn-container">
                        <a href="/Home/Account?idAccount=@Model.Email" class="btn-add">Xem thêm</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @Html.Partial("~/Views/Shared/footer.cshtml")
</body>

</html>

DLDK_Forum/DLDK_Forum/Views/Post/TableOfContents.cshtml
@model IEnumerable<DLDK_Forum.Models.ChuDe>
@{
    Layout = null;
}

<div class="table-content">
    <ul>
        <li>
            <a href="/Post/ListPost?idChuDe=">Tất cả</a>
        </li>
        @foreach (var item in Model)
        {
            <li>
                <a href="/Post/ListPost?idChuDe=@item.MaChuDe">@item.TenChuDe</a>
            </li>
        }
        <li>
            <a href="/Post/ListPost?idChuDe=CD00">Khác</a>
        </li>
    </ul>
</div>